//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BascCrudOperations.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_USER_INFO
    {
        public string USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string GENDER { get; set; }
        public string PHONE_NUMBER { get; set; }
    }
}
